# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: kaimou1357
  password: adventure
  database: mishmash_development


test:
  host: localhost
  username: kaimou1357
  password: adventure
  database: mishmash_test


production:
  <<: *default
  database: db/production.sqlite3
