default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: localhost
  username: <%= ENV.fetch("DB_USERNAME") { 5 } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mishmash_development

test:
  <<: *default
  database: mishmash_test
