default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: kaimou1357
  password: adventure
  database: mishmash_development

test:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME_TEST'] %>

production:
  <<: *default
  username: mishmash
  password: adventure
  database: mishmash_production
  host: /cloudsql/mishmash-staging:us-central1:mishmash
